//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLichProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.CatePlaces = new HashSet<CatePlace>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string pictures { get; set; }
        public int idProvince { get; set; }
        public string description { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<CatePlace> CatePlaces { get; set; }
    }
}
