//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLichProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Places = new HashSet<Place>();
            this.Foods = new HashSet<Food>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public string Contact { get; set; }
        public Nullable<double> ChildrenPrice { get; set; }
        public Nullable<double> AdultPrice { get; set; }
    
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
    }
}
